### PR TITLE
Sdhost / rpisdhc boot support

### PR DESCRIPTION
**Pull request by Googulator**

### CODE REVIEW

**Comment by SuperJMN** [comment]
Hey guys, could you please, join to our Window ARM64 on Raspberry Pi group? You can join to share our experiences with this project : it's here https://t.me/joinchat/ACWtmw7G42XInm3lAronmw

We're already 11 members and growing!

**Comment by Googulator** [comment]
I wouldn't be too worried about Arasan support, since the Arasan is necessary for WiFi and (on the 3B+ at least) Bluetooth (sdhost doesn't support SDIO). So, setting the Arasan to handle the SD card disables WiFi.

**Comment by woachk** [comment]
@SuperJMN please don't spam and split the efforts like that, ugh.

**Comment by andreiw** [comment]
Bluetooth is connected to PL011, not the miniUART. UEFI only uses the miniUART.

A

**Comment by thchi12** [comment]
I found this a little bit ubstable?
I'm now stuck at UEFI shell.And typing FS0: doesn't change to that drive...But I was abke to boot last time.

**Comment by Googulator** [comment]
Put the card in a PC, and run chkdsk on it. Sometimes the filesystem is left in an inconsistent state on shutdown, due to lack of clean ACPI shutdown support.

**Comment by andreiw** [comment]
Merged.

**Pull request closed without merging**
